Python Data types used in Machine learning programming
-----------------------------------------------------------------------------------

Python Collections (Arrays)
----------------------------------------
There are four collection data types in the Python programming language:

1. List is a collection which is ordered and changeable. Allows duplicate members.

2. Tuple is a collection which is ordered and unchangeable. Allows duplicate members.

3. Set is a collection which is unordered and unindexed. No duplicate members.

4. Dictionary is a collection which is unordered, changeable and indexed. No duplicate members.

In [1]:
#--Python Lists--> very similar to arrays
#--list can hold different types of data values

list = [ 'scikit', 123 , 2.23, 'suven', 72+3j ]
tinylist = [123, 'Technology']

print(list) 
print(list[0]) 
print(list[1:3]) #from index 1 to (3-1), i.e 2 
print(list[2:]) 
print(tinylist * 2)  # Prints list two times
print(list + tinylist) # Prints concatenated lists

['scikit', 123, 2.23, 'suven', (72+3j)]
scikit
[123, 2.23]
[2.23, 'suven', (72+3j)]
[123, 'Technology', 123, 'Technology']
['scikit', 123, 2.23, 'suven', (72+3j), 123, 'Technology']


In [4]:
#--applying few functions on the list --

few_things = "Python Java SQL R PHP JavaScript"

stuff = few_things.split(' ')

print(stuff[1])
print(stuff[-2]) # reads from right to left. here reads the 2nd last element
print(stuff.pop())
print(' '.join(stuff)) # using space as a separator
print('#'.join(stuff[3:5])) # using hash as a separator

Java
PHP
JavaScript
Python Java SQL R PHP
R#PHP


In [5]:
#--Python Tuples --> very similar to list
tuple = ('scikit', 123 , 2.23, 'suven', 72+3j)
tinytuple = (123, 'Technology')

print(tuple) 
print(tuple[0]) 
print(tuple[1:3]) # from index 1 to (3-1), i.e 2 
print(tuple[2:]) 
print(tinytuple * 2)  # Prints list two times
print(tuple + tinytuple) # Prints concatenated lists

('scikit', 123, 2.23, 'suven', (72+3j))
scikit
(123, 2.23)
(2.23, 'suven', (72+3j))
(123, 'Technology', 123, 'Technology')
('scikit', 123, 2.23, 'suven', (72+3j), 123, 'Technology')


In [6]:
#--Lists    1> uses []  2> can be updated
#--tuples   1> uses ()  2> cannot be updated  
#list can hold different types of data values
tuple = ('scikit', 123 , 2.23, 'suven', 72+3j)
list = ['tensor', 456]

#list can be updated
list[0] = "Google Tensor"
print(list[0])

#tuple cannot be updated 
tuple[0] = "ML-DL"  # see for error !!!
print(tuple[0]) 

Google Tensor


TypeError: 'tuple' object does not support item assignment

In [36]:
# sets
# A set is a collection which is unordered and unindexed. 
# In Python sets are written with curly brackets.

thisset = {"Suven", "Rocky", "Lokesh", "ML", "Neural Networks", "DL"}
print(thisset)

{'ML', 'Neural Networks', 'DL', 'Suven', 'Lokesh', 'Rocky'}


In [37]:
# Change Items
# Once a set is created, you cannot change its items, 
# but you can add new items.

# adding a new element
thisset.add("capstone projects")
print(thisset)

# see the error. Remember in SET we cannot change any item
thisset[0] = "SCTPL"

TypeError: 'set' object does not support item assignment

In [7]:
#--Python Dictionary : holds key:value pair --
#--enclosed by curly braces { } --
#--elements of dict are not ordered
dict = {}
dict['campus'] = "IIT-B"
dict[400071]= "Chembur"

tinydict={'name':'suven','code':1234,'dept':'IT sales'}

print(dict['campus']) 
print(dict[400071])
print(tinydict) #--elements of dict are not ordered
print(tinydict.keys())
print(tinydict.values()) 

IIT-B
Chembur
{'name': 'suven', 'code': 1234, 'dept': 'IT sales'}
dict_keys(['name', 'code', 'dept'])
dict_values(['suven', 1234, 'IT sales'])


In [11]:
#--more example on 
#-- Dictionary data structure --
#-- dict stores key:value pairs
# create a mapping of state to abbreviation
states = {
'Maharastra': 'MH',
'West Bengal': 'WB',
'Haryana': 'HA',
'Punjab': 'PU',
'TamilNadu': 'TN'
 }

# create a basic set of states and some cities in them
cities = {
'MH': 'Nagpur',
'WB': 'Calcutta',
'HA': 'Ambala'
}

# add some more cities
cities['PU'] = 'Amritsar'
cities['TN'] = 'Madras'

# print out some cities
print("MH State has: ", cities['MH'])
print("TN State has: ", cities['TN'])

# print some state abbreviations. key shd exactly match.
print('-' * 10)
print("Maharastra's abbreviation is: ", states['Maharastra'])
print("Punjab's abbreviation is: ", states['Punjab'])

# print every state abbreviation
print('-' * 10)
for state, abbrev in states.items():
 print(f"{state} is abbreviated {abbrev}")

# print every city in state
print('-' * 10)
for abbrev, city in cities.items():
 print(f"{abbrev} has the city {city}")

MH State has:  Nagpur
TN State has:  Madras
----------
Maharastra's abbreviation is:  MH
Punjab's abbreviation is:  PU
----------
Maharastra is abbreviated MH
West Bengal is abbreviated WB
Haryana is abbreviated HA
Punjab is abbreviated PU
TamilNadu is abbreviated TN
----------
MH has the city Nagpur
WB has the city Calcutta
HA has the city Ambala
PU has the city Amritsar
TN has the city Madras


**What is the difference between a list and a dictionary? 
>> A list is for an ordered list of items. 
>> A dictionary (or dict) is key:value pairs.

**Two more data-structures namely ndarray(from package Numpy) and dataframes(from pandas) is very much needed at every step in ML coding.   

Numpy ndarray
----------------------
All of the numeric functionality of numpy is orchestrated by two important constituents of the numpy package, 
1> ndarray and 
2> Ufuncs (Universal function). 

Numpy ndarray is a n-dimensional array object which is the core data container for all of the numpy operations. Hence called as n d => n-dimension array.

In [12]:
# Let’s create an numpy array.

import numpy as np
arr = np.array([1,3,4,5,6])
arr

array([1, 3, 4, 5, 6])

In [13]:
# shape attribute of the array object will tell us 
# about the dimensions of the array.
arr.shape  
# see below o/p : shape of 1-d array

(5,)

In [14]:
# We can stack up multiple lists to create a multidimensional array.
arr = np.array([[1,2,3],[2,4,6],[8,8,8]])
arr.shape

(3, 3)

In [16]:
# Creating and Assigning an Array with random values :

arr = np.random.randn(3,4)
arr

array([[ 0.08195782, -1.03014205, -0.90200836, -0.45982802],
       [ 0.31209609,  0.23194757,  0.14844574, -0.25416696],
       [-0.22067925, -0.32067405, -1.06182512, -1.02616913]])

In [17]:
# again dynamically creating 3-d array
arr = np.arange(12).reshape(2,2,3)
arr

# arange(n) produces elements in the given range in this case from 0 to 11
# reshape() -> shapes the elements into dimensions given
# In above case 2,2,3 -> 2 arrays , of 2 rows and 3 columns

array([[[ 0,  1,  2],
        [ 3,  4,  5]],

       [[ 6,  7,  8],
        [ 9, 10, 11]]])

In [18]:
# concept of slicing arrays 
arr = np.arange(10)
arr[5:]  # this fetches all elements from index 5 to last

array([5, 6, 7, 8, 9])

In [19]:
arr[:-5] # slices from 0 to (last-5)

array([0, 1, 2, 3, 4])

In [20]:
# #### Linear algebra using numpy

A = np.array([[1,2,3],[4,5,6],[7,8,9]])
B = np.array([[9,8,7],[6,5,4],[1,2,3]])
A.dot(B)

array([[ 24,  24,  24],
       [ 72,  69,  66],
       [120, 114, 108]])

In [21]:
# taking Transpose
A = np.arange(15).reshape(3,5)  # 3 rows and 5 columns each
A.T    # after transpose , we get 5 rows and 3 columns each

array([[ 0,  5, 10],
       [ 1,  6, 11],
       [ 2,  7, 12],
       [ 3,  8, 13],
       [ 4,  9, 14]])

Linear algebra is often also used to solve a system of equations. Using the matrix notation of system of equations and the provided function of numpy, we can easily solve such a system of equation. 
Consider the system of equations:
7x + 5y -3z = 16
3x - 5y + 2z = -8
5x + 3y - 7z = 0
This can be represented as two matrices: the coefficient matrix (a in the example) and the constants vector (b in the example).

In [22]:
a = np.array([[7,5,-3], [3,-5,2],[5,3,-7]])
b = np.array([16,-8,0])
x = np.linalg.solve(a, b)
x                             # will print the values of x,y, and z

array([1., 3., 2.])

Pandas is an important Python library for data manipulation, wrangling, 
and analysis. It functions as an intuitive and easy-to-use set of tools 
for performing operations on any kind of data.

Data Structures of Pandas:
--------------------------------------
All the data representation in pandas is done using two primary data structures:
• Series
• Dataframes

Dataframe
---------------
1> Dataframe is the most important and useful data structure, which is used for almost all kind of data representation and manipulation in pandas. Unlike numpy arrays (in general) a dataframe can contain heterogeneous data. 
2> Typically tabular data is represented using dataframes, which is analogous to an Excel sheet or a SQL table. This is extremely useful in representing raw datasets as well as processed feature sets in Machine Learning and Data Science. 
3> All the operations can be performed along the axes, rows, and
columns, in a dataframe.

In [23]:
# Just as we generally import NumPy under the alias np, 
# we will import Pandas under the alias pd:

import pandas as pd

# Example of series data type 

population_dict = {'California': 38332521,
'Texas': 26448193,
'New York': 19651127,
'Florida': 19552860,
'Illinois': 12882135}
population = pd.Series(population_dict)
population

California    38332521
Texas         26448193
New York      19651127
Florida       19552860
Illinois      12882135
dtype: int64

In [24]:
# Constructing Dataframes. Many ways.
# 1st way :
# from a series object.

pd.DataFrame(population, columns=['population'])

population
California    38332521
Texas         26448193
New York      19651127
Florida       19552860
Illinois      12882135

In [27]:
# constructing a data frame from a list of dicts.
data = [{'a': 1, 'b': 2 }, {'a': 3, 'b': 4 }]
pd.DataFrame(data)

a  b
0  1  2
1  3  4

In [28]:
# Even if some keys in the dictionary are missing, 
# Pandas will fill them in with NaN (i.e., “not a number”) values:

pd.DataFrame([{'a': 1, 'b': 2}, {'b': 3, 'c': 4}])

a  b    c
0  1.0  2  NaN
1  NaN  3  4.0

In [29]:
# Making a data frame from a two-dimensional NumPy array. 
import numpy as np
pd.DataFrame(np.random.rand(3, 2), columns=['foo', 'bar'],
index=['a', 'b', 'c'])

foo       bar
a  0.856090  0.531538
b  0.358656  0.955513
c  0.739292  0.493569

In [30]:
# List of Dictionaries to Dataframe

import pandas as pd
d =  [{'city':'Delhi',"data":1000},
      {'city':'Banglaore',"data":2000},
      {'city':'Mumbai',"data":1000}]
pd.DataFrame(d)  

# Two important things to note here: 
# first,  the keys of dictionary are picked up as the column names 
# in the dataframe 
# secondly, it picks up the default index of normal arrays.

city  data
0      Delhi  1000
1  Banglaore  2000
2     Mumbai  1000

In [31]:
# many a times , we have our datasets in CSV files
# CSV Files to Dataframe

_data = pd.read_csv(filepath_or_buffer='datasets_module_1/student_records.csv')
_data.head()  # by default first 5 records

Name OverallGrade Obedient  ResearchScore  ProjectScore Recommend
0   Henry            A        Y             90            85       Yes
1    John            C        N             85            51       Yes
2   David            F        N             10            17        No
3  Holmes            B        Y             75            71        No
4  Marvin            E        N             20            30        No

In [32]:
# extract a few columns of the dataframe
columns_numeric = ['ResearchScore','ProjectScore']
_data[columns_numeric]

ResearchScore  ProjectScore
0             90            85
1             85            51
2             10            17
3             75            71
4             20            30
5             92            79
6             60            59
7             75            33

In [33]:
# Pandas also provides us with another very handy function called describe. 
# This function will calculate the most important statistics for 
# numerical data in one go so that we don’t have to use individual functions.

_data[columns_numeric].describe()

ResearchScore  ProjectScore
count       8.000000      8.000000
mean       63.375000     53.125000
std        31.640559     24.752705
min        10.000000     17.000000
25%        50.000000     32.250000
50%        75.000000     55.000000
75%        86.250000     73.000000
max        92.000000     85.000000

In [34]:
# Like in SQL we have inner join we have merge method in pandas
# One-to-one join, is similar to the column-wise concatenation.

df1 = pd.DataFrame({'employee': ['Bob', 'Jake', 'Lisa', 'Sue'],
'group': ['Accounting', 'Engineering', 'Engineering', 'HR']})
df2 = pd.DataFrame({'employee': ['Lisa', 'Bob', 'Jake', 'Sue'],
'hire_date': [2004, 2008, 2012, 2014]})
print(df1); print(df2)

  employee        group
0      Bob   Accounting
1     Jake  Engineering
2     Lisa  Engineering
3      Sue           HR
  employee  hire_date
0     Lisa       2004
1      Bob       2008
2     Jake       2012
3      Sue       2014


In [35]:
df3 = pd.merge(df1, df2)
df3

# The pd.merge() function recognizes that each DataFrame has an 
# “employee” column, and automatically joins using this column as a key.

employee        group  hire_date
0      Bob   Accounting       2008
1     Jake  Engineering       2012
2     Lisa  Engineering       2004
3      Sue           HR       2014

**Assuming you know Python (Core + advanced) , please do recall all the above mentioned datastructures.
**The above basics of datastructures is the least one should know, before starting to learn/code this ML Course.   